package com.vaadin.starter.bakery.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.testbench.elements.ButtonElement;
import com.vaadin.testbench.elements.HorizontalLayoutElement;
import com.vaadin.testbench.elements.VerticalLayoutElement;
import com.vaadin.testbench.elementsbase.ServerClass;

@ServerClass("com.vaadin.starter.bakery.ui.MainView")
@AutoGenerated
public class MainViewElement extends HorizontalLayoutElement {

	public ButtonElement getMenuButton() {
		return $(ButtonElement.class).id("menuButton");
	}

	public ButtonElement getStorefront() {
		return $(ButtonElement.class).id("storefront");
	}

	public ButtonElement getDashboard() {
		return $(ButtonElement.class).id("dashboard");
	}

	public ButtonElement getUsers() {
		return $(ButtonElement.class).id("users");
	}

	public ButtonElement getProducts() {
		return $(ButtonElement.class).id("products");
	}

	public ButtonElement getLogout() {
		return $(ButtonElement.class).id("logout");
	}

	public VerticalLayoutElement getContent() {
		return $(VerticalLayoutElement.class).id("content");
	}
}